# This file is part of the tdwg/infrastructure.git repository.

<VirtualHost *:80>
    ServerName                 sds.tdwg.org
    ErrorLog                   logs/sds_error
    CustomLog                  logs/sds_log vhost

    Redirect                   / https://sds.tdwg.org/
</VirtualHost>

<VirtualHost *:443>
    ServerName                 sds.tdwg.org
    ErrorLog                   logs/sds_error
    CustomLog                  logs/sds_log vhosthttps
    DocumentRoot               /var/www/html/sds.tdwg.org

    <IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^([^\.]+)$ $1.html [last]
    </IfModule>

    SSLEngine       On
</VirtualHost>
