# This file is part of the tdwg/infrastructure.git repository.

<VirtualHost *:80>
    ServerName                 vms.tdwg.org
    ErrorLog                   logs/vms_error
    CustomLog                  logs/vms_log vhost

    Redirect                   / https://vms.tdwg.org/
</VirtualHost>

<VirtualHost *:443>
    ServerName                 vms.tdwg.org
    ErrorLog                   logs/vms_error
    CustomLog                  logs/vms_log vhosthttps
    DocumentRoot               /var/www/html/vms.tdwg.org

    <IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^([^\.]+)$ $1.html [last]
    </IfModule>

    SSLEngine       On
</VirtualHost>
